version: "3.9"

services:
  api:
    container_name: "caracantosmeaos-api"
    #hostname: "caracantosmeaos-api"
    image: "caracantosmeaosapi:latest"
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - TZ=$TZ
      - DEVMODE=$API_DEVMODE
      - CLUBID=$CLUBID
      - MONGO_URL=$MONGO_URL
      - CLUB_CACHE_MS=$CLUB_CACHE_MS
      - XDG_CONFIG_HOME=/tmp/.chromium
      - XDG_CACHE_HOME=/tmp/.chromium
  worker:
    container_name: "caracantosmeaos-worker"
    image: "caracantosmeaosworker:latest"
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - MONGO_URL=$MONGO_URL
      - WORKKER_INTERVAL=$WORKER_INTERVAL
      - CLUBID=$CLUBID
      - RABBITMQ_URL=$RABBITMQ_URL
      - XDG_CONFIG_HOME=/tmp/.chromium
      - XDG_CACHE_HOME=/tmp/.chromium
  web:
    container_name: "caracantosmeaos-web"
    image: "caracantosmeaosweb:latest"
    restart: unless-stopped
    volumes:
      - /home/ubuntu/dockerstacks/caracantosmeaos/web/dist:/app/dist
    ports:
      - "8081:80"
    environment:
      - TZ=$TZ
      - TZ=Europe/Madrid
  imagegenerator:
    container_name: "caracantosmeaos-imagegenerator"
    image: "caracantosmeaosimagegenerator:latest"
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - XDG_CONFIG_HOME=/tmp/.chromium
      - XDG_CACHE_HOME=/tmp/.chromium
    networks:
      caracantosmeaos_network:
        ipv4_address: 192.168.10.30
  discordbot:
    container_name: "caracantosmeaos-discordbot"
    image: "caracantosmeaosdiscordbot:latest"
    restart: unless-stopped
    volumes:
      - /home/ubuntu/dockerstacks/caracantosmeaos/discordbot/players.database.js:/app/players.database.js
    networks:
      - caracantosmeaos_network
    #ports:
    #  - "8082:80"
    environment:
      - TZ=$TZ
      - TOKEN=$DISCORD_BOT_TOKEN
      - IMAGE_GENERATOR_BASEURL=$IMAGE_GENERATOR_BASEURL  # DNS interno
      - RABBITMQ_URL=$RABBITMQ_URL


volumes:
  caracantosmeaosapi:
    name: "caracantosmeaosapi"
  caracantosmeaosweb:
    name: "caracantosmeaosweb"

networks:
  caracantosmeaos_network:
    name: "caracantosmeaos_network"
    ipam:
      config:
        - subnet: 192.168.10.0/24
